// Mechanical conversion of public-domain Natural Earth coastlines into a local SVG path.
// No borders, ancient boundaries, rivers or historical locations are inferred.
import { createHash } from 'node:crypto';
import { writeFile } from 'node:fs/promises';
const url = 'https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson';
const response = await fetch(url);
if (!response.ok) throw new Error(`Natural Earth download failed: ${response.status}`);
const bytes = await response.text();
const hash = createHash('sha256').update(bytes).digest('hex');
const expected = process.argv[2] ?? '9e0729ee253ca7d7a5c4ae9395fb1902264c5377c52e224d13dd85010e2835d9';
if (expected && hash !== expected) throw new Error(`Dataset changed: ${hash}. Review before regenerating a versioned map.`);
const data = JSON.parse(bytes);
function clip(points, axis, bound, greater) {
  const output = [];
  for (let i = 0; i < points.length; i++) {
    const a = points[i], b = points[(i + 1) % points.length];
    const insideA = greater ? a[axis] >= bound : a[axis] <= bound;
    const insideB = greater ? b[axis] >= bound : b[axis] <= bound;
    if (insideA) output.push(a);
    if (insideA !== insideB) {
      const fraction = (bound - a[axis]) / (b[axis] - a[axis]);
      output.push(a.map((value, index) => index === axis ? bound : value + fraction * (b[index] - value)));
    }
  }
  return output;
}
const paths = [];
for (const feature of data.features) {
  const polygons = feature.geometry.type === 'MultiPolygon' ? feature.geometry.coordinates : [feature.geometry.coordinates];
  for (const polygon of polygons) for (const ring of polygon) {
    let points = ring.slice(0, -1);
    for (const [axis, bound, greater] of [[0, 20, true], [0, 65, false], [1, 12, true], [1, 50, false]]) points = clip(points, axis, bound, greater);
    if (points.length >= 3) paths.push(points.map(([x, y], index) => `${index ? 'L' : 'M'}${(x * .8480480962).toFixed(5)},${(-y).toFixed(5)}`).join('') + 'Z');
  }
}
const source = `// Generated by scripts/presentations/generate-map.mjs. Public domain Natural Earth 1:110m land.\n// Source: ${url}\n// SHA256: ${hash}\n// Projection: equirectangular, standard parallel 32°N; modern coastline, not historical borders.\nexport const WEST_ASIA_LAND_V1 = ${JSON.stringify(paths.join(''))};\nexport const MAP_LONGITUDE_SCALE = .8480480962;\n`;
await writeFile(new URL('../../src/remotion/presentations/west-asia-v1.ts', import.meta.url), source);
console.log(JSON.stringify({ sha256: hash, polygons: paths.length, bytes: source.length }));
