'use client';
import React from 'react';
import { z } from 'zod';
import type { PresentationEnvelope } from '../../../lib/presentations/schema';
import { coordinateSchema } from '../../../lib/presentations/advanced-families';
import { emptySource } from '../../../lib/presentations/drafts';
import { moveItem } from '../../../lib/presentations/editing';
import { TextField, NumberField, SelectField, buttonClass } from './fields';
import { GeometryField } from './GeometryField';

export function AdvancedMapEditor({ draft, onChange }: { draft: Extract<PresentationEnvelope, { templateId: 'journey-map' | 'territory-change' }>; onChange: (draft: PresentationEnvelope) => void }) {
  const c = draft.content;
  const viewport = <div className="grid grid-cols-2 gap-2">{(['west', 'east', 'south', 'north'] as const).map(axis => <NumberField key={axis} label={`Viewport ${axis}`} value={c.viewport[axis]} onChange={value => onChange({ ...draft, content: { ...c, viewport: { ...c.viewport, [axis]: value ?? 0 } } } as typeof draft)} />)}</div>;
  if (draft.templateId === 'journey-map') {
    const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
    return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} />{viewport}<SelectField label="Route basis" value={c.mode} options={['schematic', 'supplied-route']} onChange={mode => update({ mode })} />
      <p className="text-xs text-ed-text-dim">West Asia WGS84 [longitude, latitude]. A schematic connects stops, not a known historical path. Supplied-route vertices must include every stop in order. Route geometry is never inferred from a place name.</p>
      {c.stops.map((stop, i) => { const change = (patch: Partial<typeof stop>) => update({ stops: c.stops.map(item => item.id === stop.id ? { ...item, ...patch } : item) }); return <div key={stop.id} className="space-y-2 rounded border border-ed-border p-3"><TextField label={`Stop ${i + 1}`} max={40} value={stop.label} onChange={label => change({ label })} /><TextField label={`Stop ${i + 1} date`} max={35} value={stop.date} onChange={date => change({ date })} /><div className="grid grid-cols-2 gap-2"><NumberField label={`Stop ${i + 1} longitude`} value={stop.point[0]} min={20} max={65} onChange={value => change({ point: [value ?? 0, stop.point[1]] })} /><NumberField label={`Stop ${i + 1} latitude`} value={stop.point[1]} min={12} max={50} onChange={value => change({ point: [stop.point[0], value ?? 0] })} /></div><NumberField label={`Stop ${i + 1} reveal`} min={0} value={stop.cueSeconds} onChange={value => change({ cueSeconds: value ?? 0 })} /><label className="flex gap-2 text-xs"><input type="checkbox" checked={stop.approximate} onChange={event => change({ approximate: event.target.checked })} />Approximate location</label><button type="button" className={buttonClass} disabled={i === 0} onClick={() => update({ stops: moveItem(c.stops, i, -1) })}>Move stop up</button><button type="button" className={buttonClass} disabled={c.stops.length <= 2} onClick={() => update({ stops: c.stops.filter(item => item.id !== stop.id) })}>Remove stop</button></div>; })}
      <button type="button" className={buttonClass} disabled={c.stops.length >= 5} onClick={() => update({ stops: [...c.stops, { id: crypto.randomUUID(), label: '', date: '', point: [44, 33], approximate: true, cueSeconds: c.stops.length, source: emptySource() }] })}>Add stop (up to 5)</button>
      <GeometryField<[number, number][]> label="Supplied route vertices" value={c.route} schema={z.array(coordinateSchema).max(128)} invalid={[[NaN, NaN]]} onChange={route => update({ route })} /><button type="button" className={buttonClass} onClick={() => update({ route: [], mode: 'schematic' })}>Use schematic stop connections</button></>;
  }
  const t = draft, c2 = t.content, update = (patch: Partial<typeof c2>) => onChange({ ...t, content: { ...c2, ...patch } });
  return <><TextField label="Optional heading" value={c2.heading} onChange={heading => update({ heading })} />{viewport}<TextField label="Versioned dataset / edition" max={80} value={c2.dataset} onChange={dataset => update({ dataset })} />
    <p className="text-xs text-ed-text-dim">Curated snapshots only. Each polygon is an unclosed array of [longitude, latitude] pairs. Supply 1–4 disjoint simple rings, 3–64 vertices each. Holes, antimeridian geometry and border interpolation are not supported. Use separate dated locator scenes when no reviewed polygons exist.</p>
    {c2.states.map((state, i) => { const change = (patch: Partial<typeof state>) => update({ states: c2.states.map(item => item.id === state.id ? { ...item, ...patch } : item) }); return <div key={state.id} className="space-y-2 rounded border border-ed-border p-3"><TextField label={`State ${i + 1} date`} max={35} value={state.date} onChange={date => change({ date })} /><NumberField label={`State ${i + 1} year (BCE negative)`} step={1} min={-9999} max={9999} value={state.year} onChange={value => change({ year: value ?? 0 })} /><TextField label={`State ${i + 1} label`} max={50} value={state.label} onChange={label => change({ label })} /><label className="flex gap-2 text-xs"><input type="checkbox" checked={state.approximate} onChange={event => change({ approximate: event.target.checked })} />Approximate date / boundary</label><NumberField label={`State ${i + 1} reveal`} min={0} value={state.cueSeconds} onChange={value => change({ cueSeconds: value ?? 0 })} /><GeometryField label={`State ${i + 1} polygons`} value={state.polygons} schema={z.array(z.array(coordinateSchema).min(3).max(64)).min(1).max(4)} invalid={[]} onChange={polygons => change({ polygons })} /><button type="button" className={buttonClass} disabled={c2.states.length <= 2} onClick={() => update({ states: c2.states.filter(item => item.id !== state.id) })}>Remove dated state</button></div>; })}
    <button type="button" className={buttonClass} disabled={c2.states.length >= 4} onClick={() => update({ states: [...c2.states, { id: crypto.randomUUID(), date: '', year: 0, label: '', approximate: true, cueSeconds: c2.states.at(-1)!.cueSeconds + 2, source: emptySource(), polygons: [] }] })}>Add dated state (up to 4)</button></>;
}
