'use client';
import React from 'react';
import type { PresentationEnvelope } from '../../../lib/presentations/schema';
import type { PresentationSceneReference } from '../../../lib/presentations/phase-5-validation';
import { emptyImage, emptyRegion } from '../../../lib/presentations/drafts';
import { TextField, NumberField, SelectField, buttonClass, fieldClass } from './fields';
import { RegionEditor } from './RegionEditor';
import type { PresentationAsset } from '../../../lib/presentations/schema';

export function AdvancedImageEditor({ draft, assets, references, sceneId, onChange }: { draft: PresentationEnvelope; assets: PresentationAsset[]; references: readonly PresentationSceneReference[]; sceneId?: string; onChange: (draft: PresentationEnvelope) => void }) {
  switch (draft.templateId) {
    case 'then-now': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><SelectField label="Comparison method" value={c.method} options={['side-by-side', 'wipe']} onChange={method => update({ method })} /><NumberField label="Wipe reveal (seconds)" min={0} value={c.cueSeconds} onChange={value => update({ cueSeconds: value ?? 0 })} />{c.labels.map((label, i) => <div key={i} className="space-y-2 rounded border border-ed-border p-3"><TextField label={`Time label ${i + 1}`} max={35} value={label} onChange={value => update({ labels: c.labels.map((item, j) => j === i ? value : item) as typeof c.labels })} />{(['x', 'y', 'width', 'height'] as const).map(axis => <NumberField key={axis} label={`Crop ${i + 1} ${axis}`} min={0} max={1} step={.01} value={c.crops[i][axis]} onChange={value => update({ alignmentReviewed: false, crops: c.crops.map((crop, j) => j === i ? { ...crop, [axis]: value ?? 0 } : crop) as typeof c.crops })} />)}</div>)}<label className="flex gap-2 text-xs"><input type="checkbox" checked={c.alignmentReviewed} onChange={event => update({ alignmentReviewed: event.target.checked })} />I reviewed matching landmarks in both cropped images.</label><p className="text-xs text-ed-text-dim">Preview both crops before approving alignment. Crop coordinates refer to the original image, not the output canvas. Unaligned subjects should use side-by-side. Reconstructions remain labeled.</p></>;
    }
    case 'layered-parallax': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><SelectField label="Depth camera direction" value={c.motion} options={['left', 'right', 'up', 'down']} onChange={motion => update({ motion })} />{(['x', 'y'] as const).map(axis => <NumberField key={axis} label={`Depth focal ${axis}`} min={.15} max={.85} step={.01} value={c.focalPoint[axis]} onChange={value => update({ focalPoint: { ...c.focalPoint, [axis]: value ?? .5 } })} />)}<p className="text-xs text-ed-text-dim">Upload an opaque, complete background plate and 1–3 transparent layers with the exact same pixel dimensions. Layers use shared original coordinates; individual image crops are not used. Motion is bounded with overscan. No background removal or hole filling is performed.</p>{c.layers.map((layer, i) => <div key={layer.image.id} className="space-y-2 rounded border border-ed-border p-3"><p className="text-xs">Layer {i + 1} · {layer.role}</p><NumberField label={`Layer ${i + 1} depth`} min={0} max={1} step={.05} value={layer.depth} onChange={value => update({ preparedReviewed: false, layers: c.layers.map((item,j) => j === i ? { ...item, depth: value ?? 0 } : item) })} />{i > 0 && <button type="button" className={buttonClass} disabled={c.layers.length <= 2} onClick={() => update({ preparedReviewed: false, layers: c.layers.filter((_,j) => j !== i) })}>Remove foreground layer</button>}</div>)}<button type="button" className={buttonClass} disabled={c.layers.length >= 4} onClick={() => update({ preparedReviewed: false, layers: [...c.layers, { image: emptyImage(crypto.randomUUID()), role: 'transparent', depth: Math.min(1, c.layers.at(-1)!.depth + .1) }] })}>Add foreground (up to 4 total)</button><label className="flex gap-2 text-xs"><input type="checkbox" checked={c.preparedReviewed} onChange={event => update({ preparedReviewed: event.target.checked })} />I reviewed layer registration, transparent foregrounds and a complete opaque background.</label><p className="text-xs text-ed-text-dim">If prepared layers are unavailable, use clean scene media with its existing camera treatment. This is not automatic 3D reconstruction.</p></>;
    }
    case 'structure-cutaway': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      const asset = assets.find(asset => asset.id === c.image.asset.mediaId);
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><p className="text-xs text-ed-text-dim">Select sections of an already-authored cutaway. The renderer exposes existing pixels, not a generated interior. For an ordinary photograph use Detail Annotation instead.</p>{c.sections.map((section, i) => <div key={section.id} className="space-y-2 rounded border border-ed-border p-3"><RegionEditor region={section} url={asset?.url} onChange={patch => update({ diagramReviewed: false, sections: c.sections.map(item => item.id === section.id ? { ...item, ...patch } : item) })} /><TextField label={`Section ${i + 1} description`} max={80} multiline value={section.description} onChange={description => update({ sections: c.sections.map(item => item.id === section.id ? { ...item, description } : item) })} /><button type="button" className={buttonClass} disabled={c.sections.length <= 2} onClick={() => update({ sections: c.sections.filter(item => item.id !== section.id) })}>Remove section</button></div>)}<button type="button" className={buttonClass} disabled={c.sections.length >= 4} onClick={() => update({ diagramReviewed: false, sections: [...c.sections, { ...emptyRegion(c.sections.length + 10), id: crypto.randomUUID(), description: '' }] })}>Add section (up to 4)</button><label className="flex gap-2 text-xs"><input type="checkbox" checked={c.diagramReviewed} onChange={event => update({ diagramReviewed: event.target.checked })} />I reviewed the authored cutaway and its section geometry.</label></>;
    }
    case 'chapter-recap': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } }), current = references.find(scene => scene.id === sceneId);
      const earlier = references.filter(scene => (!current || scene.sequence < current.sequence) && assets.some(asset => asset.id === scene.mediaId));
      return <><TextField label="Chapter title" max={90} value={c.heading} onChange={heading => update({ heading })} /><TextField label="Next chapter cue" max={70} value={c.nextCue} onChange={nextCue => update({ nextCue })} /><p className="text-xs text-ed-text-dim">Choose earlier scenes with linked still images. The still is reused without nesting a video. Deleted, reordered or changed source scenes require repair. A source packet can be approved before choosing the eventual recap scene; earlier-scene order is checked again on Apply.</p>{c.items.map((item, i) => <div key={item.id} className="space-y-2 rounded border border-ed-border p-3"><label className="block text-xs">Recap scene {i + 1}<select aria-label={`Recap scene ${i + 1}`} className={fieldClass} value={item.sceneId} onChange={event => { const source = references.find(scene => scene.id === event.target.value); update({ items: c.items.map(entry => entry.id === item.id ? { ...entry, sceneId: source?.id ?? '', image: { ...entry.image, asset: { kind: 'media', mediaId: source?.mediaId ?? '' } } } : entry) }); }}><option value="">Choose an earlier scene image</option>{earlier.map(scene => <option key={scene.id} value={scene.id}>Scene {scene.sequence} · {assets.find(asset => asset.id === scene.mediaId)?.name}</option>)}</select></label><TextField label={`Takeaway ${i + 1}`} max={70} value={item.takeaway} onChange={takeaway => update({ items: c.items.map(entry => entry.id === item.id ? { ...entry, takeaway } : entry) })} /><button type="button" className={buttonClass} disabled={c.items.length <= 2} onClick={() => update({ items: c.items.filter(entry => entry.id !== item.id) })}>Remove recap item</button></div>)}<button type="button" className={buttonClass} disabled={c.items.length >= 4} onClick={() => update({ items: [...c.items, { id: crypto.randomUUID(), sceneId: '', image: emptyImage(crypto.randomUUID()), takeaway: '' }] })}>Add recap item (up to 4)</button></>;
    }
    default: return null;
  }
}
