'use client';
import React from 'react';
import type { PresentationEnvelope } from '../../../lib/presentations/schema';
import { TextField, NumberField, SelectField, buttonClass } from './fields';

export function ChartEditor({ draft, onChange }: { draft: Extract<PresentationEnvelope, { templateId: 'animated-chart' }>; onChange: (draft: PresentationEnvelope) => void }) {
  const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
  return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><SelectField label="Chart type" value={c.kind} options={['bar', 'line']} onChange={kind => update({ kind })} /><TextField label="Chart unit" max={20} value={c.unit} onChange={unit => update({ unit })} /><TextField label="X axis meaning" max={40} value={c.axisLabel} onChange={axisLabel => update({ axisLabel })} /><TextField label="Dataset caveat / scope" max={100} multiline value={c.caveat} onChange={caveat => update({ caveat })} /><p className="text-xs text-ed-text-dim">Initial scope: 2–6 non-negative points, zero y baseline. Blank value means missing, not zero. Lines use actual increasing x coordinates and break at missing values. Bounds must bracket the value. Credit the dataset on Sources.</p>{c.points.map((point, i) => { const change = (patch: Partial<typeof point>) => update({ points: c.points.map(item => item.id === point.id ? { ...item, ...patch } : item) }); return <div key={point.id} className="space-y-2 rounded border border-ed-border p-3"><TextField label={`Point ${i + 1} label`} max={25} value={point.label} onChange={label => change({ label })} /><NumberField label={`Point ${i + 1} x`} value={point.x} onChange={value => change({ x: value ?? 0 })} /><NumberField label={`Point ${i + 1} value (blank = missing)`} min={0} value={point.value} onChange={value => change({ value })} /><div className="grid grid-cols-2 gap-2"><NumberField label={`Point ${i + 1} lower bound`} min={0} value={point.low} onChange={low => change({ low })} /><NumberField label={`Point ${i + 1} upper bound`} min={0} value={point.high} onChange={high => change({ high })} /></div><label className="flex gap-2 text-xs"><input type="checkbox" checked={point.estimated} onChange={event => change({ estimated: event.target.checked })} />Estimated value</label><button type="button" className={buttonClass} disabled={c.points.length <= 2} onClick={() => update({ points: c.points.filter(item => item.id !== point.id) })}>Remove data point</button></div>; })}<button type="button" className={buttonClass} disabled={c.points.length >= 6} onClick={() => update({ points: [...c.points, { id: crypto.randomUUID(), label: '', x: c.points.at(-1)!.x + 1, value: null, low: null, high: null, estimated: false }] })}>Add data point (up to 6)</button></>;
}
