'use client';
import React, { useRef } from 'react';
import type { PresentationAsset, PresentationEnvelope } from '../../../lib/presentations/schema';
import { presentationImages } from '../../../lib/presentations/content';
import { updatePresentationImage, moveItem } from '../../../lib/presentations/editing';
import { emptyImage, emptyRegion, emptySource } from '../../../lib/presentations/drafts';
import { TextField, NumberField, SelectField, ImageEditor, fieldClass, buttonClass } from './fields';
import { RegionEditor } from './RegionEditor';
import { historicalDateLabel } from '../../../lib/presentations/dates';
import { PHASE_4_FAMILIES, PHASE_5_FAMILIES } from '../../../lib/presentations/registry';
import { Phase4ContentEditor } from './Phase4ContentEditor';
import { Phase5ContentEditor } from './Phase5ContentEditor';
import type { PresentationSceneReference } from '../../../lib/presentations/phase-5-validation';

type Props = { draft: PresentationEnvelope; assets: PresentationAsset[]; onChange: (draft: PresentationEnvelope) => void; dateConvention?: 'BCE/CE' | 'BC/AD'; references?: readonly PresentationSceneReference[]; sceneId?: string };
function FamilyFields({ draft, assets, onChange, dateConvention = 'BCE/CE', references = [], sceneId }: Props) {
  const body = useRef<HTMLTextAreaElement>(null);
  if (PHASE_4_FAMILIES.some(id => id === draft.templateId)) return <Phase4ContentEditor draft={draft} onChange={onChange} />;
  if (PHASE_5_FAMILIES.some(id => id === draft.templateId)) return <Phase5ContentEditor draft={draft} assets={assets} references={references} sceneId={sceneId} onChange={onChange} />;
  switch (draft.templateId) {
    case 'clean': return <p className="text-xs">No presentation. Keep the underlying scene media.</p>;
    case 'image-comparison': return <><TextField label="Optional heading" value={draft.content.heading} onChange={heading => onChange({ ...draft, content: { ...draft.content, heading } })} /><button type="button" className={buttonClass} onClick={() => onChange({ ...draft, content: { ...draft.content, images: [draft.content.images[1], draft.content.images[0]] } })}>Swap images and labels</button></>;
    case 'historical-timeline': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><SelectField label="Timeline spacing" value={c.spacing} options={['equal', 'proportional']} onChange={spacing => update({ spacing })} />
        <p className="text-xs text-ed-text-dim">Negative numeric years mean BCE; positive years mean CE. No year zero. Display labels are yours; numeric years are only needed for proportional spacing.</p>
        {c.events.map((event, index) => { const change = (patch: Partial<typeof event>) => update({ events: c.events.map(item => item.id === event.id ? { ...item, ...patch } : item) }); return <div key={event.id} className="space-y-2 rounded-lg border border-ed-border p-3"><h4 className="text-xs font-semibold">Event {index + 1}</h4><div className="flex gap-1"><button type="button" className={buttonClass} disabled={index === 0} onClick={() => update({ events: moveItem(c.events,index,-1) })}>Move event up</button><button type="button" className={buttonClass} disabled={index === c.events.length-1} onClick={() => update({ events: moveItem(c.events,index,1) })}>Move event down</button></div><TextField label="Displayed date" max={40} value={event.date.display} onChange={display => change({ date: { ...event.date, display } })} /><label className="flex gap-2 text-xs"><input type="checkbox" checked={event.date.approximate} onChange={e => change({ date: { ...event.date, approximate: e.target.checked } })} />Approximate date (c.)</label><div className="grid grid-cols-2 gap-2"><NumberField label="Start year (optional)" step={1} min={-9999} max={9999} value={event.date.year} onChange={year => change({ date: { ...event.date, year } })} /><NumberField label="Range end (optional)" step={1} min={-9999} max={9999} value={event.date.endYear} onChange={endYear => change({ date: { ...event.date, endYear } })} /></div><button type="button" className={buttonClass} disabled={event.date.year === null || event.date.year === 0} onClick={() => change({ date: { ...event.date, display: historicalDateLabel(event.date.year!, event.date.endYear, dateConvention) } })}>Use numeric date label</button><TextField label="Event label" max={65} value={event.label} onChange={label => change({ label })} /><NumberField label="Event reveal (seconds)" min={0} value={event.cueSeconds} onChange={value => change({ cueSeconds: value ?? 0 })} /><label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(event.image)} onChange={e => change({ image: e.target.checked ? emptyImage(crypto.randomUUID()) : null })} />Optional event image</label><button type="button" className={buttonClass} disabled={c.events.length <= 1} onClick={() => update({ events: c.events.filter(item => item.id !== event.id) })}>Remove event</button></div>; })}
        <button type="button" className={buttonClass} disabled={c.events.length >= 5} onClick={() => update({ events: [...c.events, { id: crypto.randomUUID(), date: { display: '', approximate: false, year: null, endYear: null }, label: '', image: null, source: emptySource(), cueSeconds: c.events.length }] })}>Add event (up to 5)</button></>;
    }
    case 'person-introduction': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Person name" max={80} value={c.name} onChange={name => update({ name })} /><TextField label="Role" max={80} value={c.role} onChange={role => update({ role })} /><TextField label="Affiliation (optional)" max={70} value={c.affiliation} onChange={affiliation => update({ affiliation })} /><TextField label="Dates (optional)" max={40} value={c.dates} onChange={dates => update({ dates })} /><label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(c.portrait)} onChange={e => update({ portrait: e.target.checked ? emptyImage(crypto.randomUUID()) : null })} />Include a portrait</label><SelectField label="Portrait side" value={c.side} options={['left', 'right']} onChange={side => update({ side })} /><SelectField label="Portrait treatment" value={c.treatment} options={['framed', 'cutout']} onChange={treatment => update({ treatment })} /><p className="text-xs text-ed-text-dim">Cutout requires a supplied transparent image. We do not remove backgrounds or invent a person’s portrait.</p></>;
    }
    case 'archival-explainer': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Kicker (optional)" max={50} value={c.kicker} onChange={kicker => update({ kicker })} /><TextField label="Heading" value={c.heading} onChange={heading => update({ heading })} /><SelectField label="Text kind" value={c.textKind} options={['explanation', 'quotation']} onChange={textKind => update({ textKind })} /><label className="block text-xs">Body<textarea aria-label="Body" ref={body} className={`${fieldClass} mt-1 min-h-40`} maxLength={550} value={c.body} onChange={e => update({ body: e.target.value, highlights: [] })} /></label><p className="text-xs text-ed-text-dim">Aim for 18–30 words in portrait, 35–55 in landscape. Editing body text clears highlights so they cannot move to the wrong passage.</p><button type="button" className={buttonClass} disabled={c.highlights.length >= 4} onClick={() => { const start = body.current?.selectionStart ?? 0, end = body.current?.selectionEnd ?? 0; if (end > start) update({ highlights: [...c.highlights, { start, end, cueSeconds: 1 }] }); }}>Highlight selected body text</button>{c.highlights.map((range, index) => <div key={`${range.start}:${range.end}`} className="space-y-2 rounded border border-ed-border p-2"><p className="text-xs">“{c.body.slice(range.start, range.end)}”</p><NumberField label={`Highlight ${index + 1} reveal (seconds)`} min={0} value={range.cueSeconds} onChange={value => update({ highlights: c.highlights.map((item, i) => i === index ? { ...item, cueSeconds: value ?? 0 } : item) })} /><button type="button" className={buttonClass} onClick={() => update({ highlights: c.highlights.filter((_, i) => i !== index) })}>Remove highlight</button></div>)}</>;
    }
    case 'map-locator': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><p className="text-xs text-ed-text-dim">West Asia regional map · bundled modern coastline · 20–65°E, 12–50°N. Enter verified coordinates, not inferred historical borders.</p>
        <div className="grid grid-cols-2 gap-2">{(['west', 'east', 'south', 'north'] as const).map(key => <NumberField key={key} label={`Viewport ${key}`} value={c.viewport[key]} onChange={value => update({ viewport: { ...c.viewport, [key]: value ?? 0 } })} />)}</div>
        {c.markers.map((marker, index) => { const change = (patch: Partial<typeof marker>) => update({ markers: c.markers.map(item => item.id === marker.id ? { ...item, ...patch } : item) }); return <div key={marker.id} className="space-y-2 rounded-lg border border-ed-border p-3"><h4 className="text-xs font-semibold">Marker {index + 1}</h4><TextField label="Place label" max={45} value={marker.label} onChange={label => change({ label })} /><NumberField label="Latitude" min={12} max={50} value={marker.latitude} step={.001} onChange={value => change({ latitude: value ?? 0 })} /><NumberField label="Longitude" min={20} max={65} value={marker.longitude} step={.001} onChange={value => change({ longitude: value ?? 0 })} /><label className="flex gap-2 text-xs"><input type="checkbox" checked={marker.approximate} onChange={e => change({ approximate: e.target.checked })} />Approximate location</label><NumberField label="Marker reveal (seconds)" value={marker.cueSeconds} min={0} onChange={value => change({ cueSeconds: value ?? 0 })} /><button type="button" className={buttonClass} disabled={c.markers.length <= 1} onClick={() => update({ markers: c.markers.filter(item => item.id !== marker.id) })}>Remove marker</button></div>; })}<button type="button" className={buttonClass} disabled={c.markers.length >= 4} onClick={() => update({ markers: [...c.markers, { id: crypto.randomUUID(), label: '', latitude: 33, longitude: 44, approximate: false, cueSeconds: c.markers.length, source: emptySource() }] })}>Add marker (up to 4)</button></>;
    }
    case 'artifact-spotlight': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Artifact title" max={90} value={c.heading} onChange={heading => update({ heading })} />{c.metadata.map(item => <div key={item.id} className="space-y-2 rounded border border-ed-border p-2"><TextField label="Metadata label" max={25} value={item.label} onChange={label => update({ metadata: c.metadata.map(row => row.id === item.id ? { ...row, label } : row) })} /><TextField label="Metadata value" max={65} value={item.value} onChange={value => update({ metadata: c.metadata.map(row => row.id === item.id ? { ...row, value } : row) })} /><button type="button" className={buttonClass} onClick={() => update({ metadata: c.metadata.filter(row => row.id !== item.id) })}>Remove metadata</button></div>)}<button type="button" className={buttonClass} disabled={c.metadata.length >= 4} onClick={() => update({ metadata: [...c.metadata, { id: crypto.randomUUID(), label: '', value: '' }] })}>Add metadata (up to 4)</button><p className="text-xs text-ed-text-dim">Use supplied material, date, dimensions, institution or catalogue number. No synthetic 3D reconstruction.</p></>;
    }
    case 'detail-annotation': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      const url = assets.find(asset => asset.id === c.image.asset.mediaId)?.url;
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} />{c.regions.map(region => <div key={region.id}><RegionEditor region={region} url={url} onChange={value => update({ regions: c.regions.map(item => item.id === region.id ? value : item) })} /><button type="button" className={buttonClass} disabled={c.regions.length <= 1} onClick={() => update({ regions: c.regions.filter(item => item.id !== region.id) })}>Remove region</button></div>)}<button type="button" className={buttonClass} disabled={c.regions.length >= 3} onClick={() => update({ regions: [...c.regions, { ...emptyRegion(1), id: crypto.randomUUID(), cueSeconds: c.regions.length * 2 }] })}>Add region (up to 3)</button></>;
    }
    case 'manuscript-highlight': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><TextField label="Edition / source" max={90} value={c.edition} onChange={edition => update({ edition })} /><TextField label="Page / folio" max={45} value={c.folio} onChange={folio => update({ folio })} /><RegionEditor region={c.region} url={assets.find(asset => asset.id === c.image.asset.mediaId)?.url} onChange={region => update({ region })} /><TextField label="Supplied excerpt (optional)" max={220} multiline value={c.excerpt} onChange={excerpt => update({ excerpt })} /><TextField label="Supplied translation (optional)" max={220} multiline value={c.translation} onChange={translation => update({ translation })} /><p className="text-xs text-ed-text-dim">Use a real source image. OCR and AI transcription are not part of this phase. For original-script typography, use Original Text → Translation.</p></>;
    }
    case 'text-translation': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><TextField label="Language" max={45} value={c.language} onChange={language => update({ language })} /><SelectField label="Original script" value={c.script} options={['latin', 'hebrew', 'syriac', 'ethiopic', 'cuneiform', 'transliteration-only']} onChange={script => update({ script, direction: script === 'hebrew' || script === 'syriac' ? 'rtl' : 'ltr' })} /><SelectField label="Original direction" value={c.direction} options={['ltr', 'rtl']} onChange={direction => update({ direction })} /><TextField label="Exact supplied original" max={200} multiline value={c.original} onChange={original => update({ original })} /><TextField label="Transliteration (optional)" max={200} multiline value={c.transliteration} onChange={transliteration => update({ transliteration })} /><TextField label="Supplied translation" max={240} multiline value={c.translation} onChange={translation => update({ translation })} /><TextField label="Edition / attribution" max={90} value={c.edition} onChange={edition => update({ edition })} /><NumberField label="Translation reveal (seconds)" value={c.cueSeconds} min={0} onChange={value => update({ cueSeconds: value ?? 0 })} />{c.script === 'transliteration-only' && <label className="flex gap-2 text-xs"><input type="checkbox" checked={c.fallbackReviewed} onChange={e => update({ fallbackReviewed: e.target.checked })} />I reviewed this transliteration fallback</label>}<p className="text-xs text-ed-text-dim">No generated translation. Supported fonts: Latin, Hebrew, Syriac, Ethiopic, cuneiform. Complex-script text reveals as a whole phrase, never character by character.</p></>;
    }
    case 'relationship-diagram': {
      const c = draft.content, update = (patch: Partial<typeof c>) => onChange({ ...draft, content: { ...c, ...patch } });
      return <><TextField label="Optional heading" value={c.heading} onChange={heading => update({ heading })} /><TextField label="Source / tradition context" max={85} value={c.context} onChange={context => update({ context })} /><SelectField label="Diagram layout" value={c.layout} options={['chain', 'hub', 'tree']} onChange={layout => update({ layout })} />
        {c.nodes.map((node, index) => <div key={node.id} className="space-y-2 rounded border border-ed-border p-2"><TextField label={`Node ${index + 1}`} max={45} value={node.label} onChange={label => update({ nodes: c.nodes.map(item => item.id === node.id ? { ...item, label } : item) })} /><div className="flex gap-1"><button type="button" className={buttonClass} disabled={index === 0} onClick={() => update({ nodes: moveItem(c.nodes,index,-1) })}>Move node up</button><button type="button" className={buttonClass} disabled={index === c.nodes.length-1} onClick={() => update({ nodes: moveItem(c.nodes,index,1) })}>Move node down</button></div><label className="flex gap-2 text-xs"><input type="checkbox" checked={Boolean(node.image)} onChange={e => update({ nodes: c.nodes.map(item => item.id === node.id ? { ...item, image: e.target.checked ? emptyImage(crypto.randomUUID()) : null } : item) })} />Optional node image</label><button type="button" className={buttonClass} disabled={c.nodes.length <= 2} onClick={() => update({ nodes: c.nodes.filter(item => item.id !== node.id), edges: c.edges.filter(edge => edge.from !== node.id && edge.to !== node.id) })}>Remove node and its edges</button></div>)}
        <button type="button" className={buttonClass} disabled={c.nodes.length >= 6} onClick={() => update({ nodes: [...c.nodes, { id: crypto.randomUUID(), label: '', image: null }] })}>Add node (up to 6)</button>
        {c.edges.map((edge, index) => { const change = (patch: Partial<typeof edge>) => update({ edges: c.edges.map(item => item.id === edge.id ? { ...item, ...patch } : item) }); return <div key={edge.id} className="space-y-2 rounded border border-ed-border p-2"><h4 className="text-xs font-semibold">Relationship {index + 1}</h4>{(['from', 'to'] as const).map(key => <label key={key} className="block text-xs">{key}<select aria-label={`Relationship ${index + 1} ${key}`} className={fieldClass} value={edge[key]} onChange={e => change({ [key]: e.target.value })}>{c.nodes.map((node, i) => <option key={node.id} value={node.id}>{node.label || `Node ${i + 1}`}</option>)}</select></label>)}<TextField label="Relationship label" max={35} value={edge.label} onChange={label => change({ label })} /><SelectField label="Relationship type" value={edge.type} options={['relationship', 'influence', 'tradition', 'uncertain']} onChange={type => change({ type })} /><NumberField label="Relationship reveal (seconds)" min={0} value={edge.cueSeconds} onChange={value => change({ cueSeconds: value ?? 0 })} /><button type="button" className={buttonClass} onClick={() => update({ edges: c.edges.filter(item => item.id !== edge.id) })}>Remove relationship</button></div>; })}<button type="button" className={buttonClass} disabled={c.edges.length >= 7} onClick={() => update({ edges: [...c.edges, { id: crypto.randomUUID(), from: c.nodes[0].id, to: c.nodes[1].id, label: '', type: 'relationship', source: emptySource(), cueSeconds: 1 }] })}>Add relationship</button><p className="text-xs text-ed-text-dim">Small connected graphs only. Dense networks must be split into more scenes. Each edge needs a source credit on Sources.</p></>;
    }
  }
}

export function ContentEditor(props: Props) {
  return <><FamilyFields {...props} />{presentationImages(props.draft).map((image, index) => <ImageEditor key={image.id} image={image} label={`Image ${index + 1}`} assets={props.assets} geometry={!["then-now","layered-parallax","structure-cutaway"].includes(props.draft.templateId)} onChange={patch => props.onChange(updatePresentationImage(props.draft, image.id, patch))} />)}</>;
}
