import React from 'react';
import type { PresentationEnvelope, ResolvedPresentation } from '../../lib/presentations/schema';
import { Heading, Copy, reveal, type StageStyle } from './Stage';
import { SourceImage } from './CoreFamilies';

export function AdvancedSourceFamily({ envelope, presentation, style }: { envelope: PresentationEnvelope; presentation: ResolvedPresentation; style: StageStyle }) {
  if (envelope.templateId === 'manuscript-comparison') {
    const c = envelope.content;
    return <div style={{ height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 24 * style.unit }}><Heading style={style}>{c.heading}</Heading><div style={{ display: 'grid', gridTemplateColumns: style.portrait || style.square ? '1fr' : '1fr 1fr', gap: 24 * style.unit }}>{c.passages.map((passage, i) => {
      const text = passage.script === 'transliteration-only' ? passage.transliteration : passage.text, side = i === 0 ? 'left' : 'right';
      const parts: React.ReactNode[] = []; let cursor = 0;
      for (const mapping of [...c.mappings].sort((a,b) => a[`${side}Start`] - b[`${side}Start`])) { const start = mapping[`${side}Start`], end = mapping[`${side}End`]; parts.push(text.slice(cursor,start), <mark key={mapping.id} style={{ color: 'inherit', background: reveal(style.frame,style.fps,mapping.cueSeconds) > 0 ? style.theme.accent + '66' : 'transparent' }}>{text.slice(start,end)}</mark>); cursor = end; }
      parts.push(text.slice(cursor));
      return <div key={i} data-fit-height style={{ padding: 24 * style.unit, background: style.theme.surface }}><Copy style={style} size={26}>{passage.edition} · {passage.language}</Copy><div data-fit dir={passage.script === 'transliteration-only' ? 'ltr' : passage.direction} style={{ fontFamily: style.comparisonFonts?.[i], fontSize: (passage.script === 'cuneiform' ? 46 : 38) * style.unit, lineHeight: 1.65, whiteSpace: 'pre-wrap', unicodeBidi: 'isolate', overflowWrap: 'anywhere', marginTop: 16 * style.unit }}>{parts}</div><Copy style={style} size={22}>{passage.script === 'transliteration-only' ? 'Reviewed transliteration fallback' : 'Exact supplied passage'}</Copy></div>;
    })}</div>{c.mappings.map((mapping,i) => <div key={mapping.id} style={{ opacity: reveal(style.frame,style.fps,mapping.cueSeconds) }}><Copy style={style} size={28}>{i + 1} · {mapping.label}</Copy></div>)}<Copy style={style} size={24}>Authored segment mappings · no automatic translation or textual authority ranking</Copy></div>;
  }
  if (envelope.templateId === 'evidence-board') {
    const c = envelope.content, active = [...c.links].reverse().find(link => style.frame / style.fps >= link.cueSeconds);
    return <div style={{ height: '100%', display: 'flex', flexDirection: 'column', gap: 20 * style.unit }}><Heading style={style}>{c.heading}</Heading><div style={{ flex: 1, minHeight: 0, display: 'grid', gridTemplateColumns: style.portrait ? '1fr' : c.cards.length > 4 ? '1fr 1fr 1fr' : '1fr 1fr', gridTemplateRows: `repeat(${style.portrait ? c.cards.length : Math.ceil(c.cards.length / (c.cards.length > 4 ? 3 : 2))}, minmax(0,1fr))`, gap: 16 * style.unit }}>{c.cards.map((card,i) => <div key={card.id} data-fit-height data-evidence-card={card.id} style={{ minHeight: 0, display: 'flex', flexDirection: style.portrait ? 'row' : 'column', gap: 10 * style.unit, padding: 16 * style.unit, background: style.theme.surface, border: `${2 * style.unit}px solid ${active && [active.from,active.to].includes(card.id) ? style.theme.accent : 'transparent'}` }}>{card.image && <div style={{ flex: 1, minHeight: 0 }}><SourceImage image={card.image} presentation={presentation} style={style} /></div>}<div style={{ flexGrow: style.portrait ? 2 : 0, flexBasis: style.portrait ? 0 : 'auto', flexShrink: 0 }}><Copy style={style} size={30}>{i + 1} · {card.label}</Copy><Copy style={style} size={26}>{card.detail}</Copy></div></div>)}</div><div style={{ display: 'grid', gap: 8 * style.unit }}>{c.links.map(link => <div key={link.id} style={{ opacity: reveal(style.frame,style.fps,link.cueSeconds) }}><Copy style={style} size={26}>{c.cards.findIndex(card => card.id === link.from) + 1} ↔ {c.cards.findIndex(card => card.id === link.to) + 1} · {link.label}</Copy></div>)}</div><Copy style={style} size={22}>Explained relationships · connections are not proof</Copy></div>;
  }
  if (envelope.templateId === 'competing-explanations') {
    const c = envelope.content;
    return <div style={{ height: '100%', display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 24 * style.unit }}><Heading style={style}>{c.heading}</Heading><div style={{ display: 'grid', gridTemplateColumns: style.portrait || style.square ? '1fr' : `repeat(${c.explanations.length},minmax(0,1fr))`, gap: 20 * style.unit }}>{(style.square ? [c.explanations[Math.min(c.explanations.length - 1, Math.floor(style.frame / Math.max(1,presentation.durationInFrames / c.explanations.length)))]] : c.explanations).map((item,i) => <div key={item.id} data-fit-height style={{ background: style.theme.surface, padding: 24 * style.unit, display: 'flex', flexDirection: 'column', gap: 16 * style.unit, opacity: reveal(style.frame,style.fps,style.square ? 0 : i * .4) }}><Copy style={style} size={38}>{item.name}</Copy><div><Copy style={style} size={23}>SUPPLIED SUPPORT</Copy><Copy style={style} size={30}>{item.support}</Copy></div><div><Copy style={style} size={23}>UNRESOLVED / LIMITS</Copy><Copy style={style} size={28}>{item.limitation}</Copy></div></div>)}</div><Copy style={style} size={24}>Attributed explanations · equal space does not imply equal evidence</Copy></div>;
  }
  return null;
}
