"use client";

import React, { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import Link from "next/link";

interface Scene {
  id: string;
  text: string;
  bRollKeyword: string;
  durationInFrames: number;
}

export default function TimelineEditorPage() {
  const params = useParams();
  const router = useRouter();
  const slug = params.slug as string;
  
  const [timeline, setTimeline] = useState<Scene[]>([]);
  const [selectedScene, setSelectedScene] = useState<Scene | null>(null);
  const [isCompiling, setIsCompiling] = useState(false);

  useEffect(() => {
    // Load the JSON generated by our Phase 2 AI
    const saved = localStorage.getItem('temp_video_timeline');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setTimeline(parsed.scenes);
        setSelectedScene(parsed.scenes[0]); // Auto-select first scene
      } catch (e) {
        console.error("Failed to parse timeline JSON");
      }
    }
  }, []);

  const handleUpdateScene = (field: keyof Scene, value: string) => {
    if (!selectedScene) return;
    
    const updatedScene = { ...selectedScene, [field]: value };
    setSelectedScene(updatedScene);
    
    setTimeline(prev => prev.map(s => s.id === updatedScene.id ? updatedScene : s));
  };

  const handleCompile = () => {
    setIsCompiling(true);
    // Phase 4: Send finalized JSON to Remotion Lambda
    setTimeout(() => {
      alert("Timeline compiled and sent to rendering engine!");
      setIsCompiling(false);
      router.push(`/workspaces/${slug}`);
    }, 2000);
  };

  if (timeline.length === 0) {
    return <div style={{ padding: '4rem', textAlign: 'center' }}>Loading Timeline...</div>;
  }

  // Calculate total duration for visual scaling
  const totalFrames = timeline.reduce((acc, scene) => acc + scene.durationInFrames, 0);
  const totalSeconds = Math.floor(totalFrames / 30); // Assuming 30fps

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', background: '#0a0a0f', margin: '-1.5rem', padding: '0' }}>
      
      {/* Top Navbar */}
      <header style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1rem 2rem', borderBottom: '1px solid var(--border-color)', background: 'var(--bg-secondary)' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
          <button className="btn-secondary" onClick={() => router.push(`/workspaces/${slug}`)}>
            &larr; Exit
          </button>
          <h2 style={{ fontSize: '1.2rem', fontWeight: '600' }}>Vibe Editor: <span style={{ color: 'var(--text-secondary)' }}>Generated Script</span></h2>
        </div>
        
        <div style={{ display: 'flex', gap: '1rem' }}>
          <button className="btn-secondary">
            Settings
          </button>
          <button 
            className="btn-primary" 
            style={{ background: 'linear-gradient(135deg, #00ffcc, #0066ff)' }}
            onClick={handleCompile}
            disabled={isCompiling}
          >
            {isCompiling ? "Compiling to Cloud..." : "Compile Final Video"}
          </button>
        </div>
      </header>

      {/* Main Workspace (Preview + Properties) */}
      <div style={{ display: 'flex', flex: 1, overflow: 'hidden' }}>
        
        {/* Left: Video Preview Area */}
        <div style={{ flex: 2, display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#000', borderRight: '1px solid var(--border-color)', position: 'relative' }}>
          <div style={{ 
            width: '360px', 
            height: '640px', // 9:16 aspect ratio
            background: '#1a1a24', 
            border: '1px solid var(--border-color)',
            borderRadius: '12px',
            position: 'relative',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            overflow: 'hidden'
          }}>
            {/* Mock B-Roll Layer */}
            <div style={{ position: 'absolute', inset: 0, opacity: 0.5, backgroundImage: 'url("https://images.unsplash.com/photo-1620712943543-bcc4688e7485?q=80&w=600&auto=format&fit=crop")', backgroundSize: 'cover', backgroundPosition: 'center' }}></div>
            
            {/* Mock Subtitles */}
            <div style={{ zIndex: 10, width: '80%', textAlign: 'center', background: 'rgba(0,0,0,0.6)', padding: '0.5rem', borderRadius: '8px' }}>
              <p style={{ fontSize: '1.2rem', fontWeight: 'bold', color: '#fff', textTransform: 'uppercase' }}>
                {selectedScene?.text.split(' ').slice(0, 4).join(' ')}...
              </p>
            </div>

            <div style={{ position: 'absolute', top: '10px', right: '10px', background: 'rgba(0,0,0,0.8)', padding: '4px 8px', borderRadius: '4px', fontSize: '0.7rem' }}>
              B-Roll: {selectedScene?.bRollKeyword}
            </div>
          </div>

          {/* Player Controls */}
          <div style={{ position: 'absolute', bottom: '20px', display: 'flex', gap: '1rem', background: 'var(--bg-glass)', padding: '0.5rem 1rem', borderRadius: '8px', backdropFilter: 'blur(10px)' }}>
            <button style={{ color: 'white' }}>&#9658; Play</button>
            <span style={{ color: 'var(--text-secondary)' }}>00:00 / 00:{totalSeconds < 10 ? `0${totalSeconds}` : totalSeconds}</span>
          </div>
        </div>

        {/* Right: Scene Properties Inspector */}
        <div style={{ width: '350px', background: 'var(--bg-secondary)', padding: '1.5rem', overflowY: 'auto' }}>
          <h3 style={{ fontSize: '1.1rem', fontWeight: '600', marginBottom: '1.5rem' }}>Block Editor</h3>
          
          {selectedScene ? (
            <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
              <div>
                <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>Narration Text</label>
                <textarea 
                  className="input-field" 
                  style={{ minHeight: '120px', resize: 'vertical' }}
                  value={selectedScene.text}
                  onChange={(e) => handleUpdateScene('text', e.target.value)}
                />
              </div>

              <div>
                <label style={{ display: 'block', fontSize: '0.85rem', color: 'var(--text-secondary)', marginBottom: '0.5rem' }}>B-Roll Generation Prompt</label>
                <input 
                  type="text" 
                  className="input-field" 
                  value={selectedScene.bRollKeyword}
                  onChange={(e) => handleUpdateScene('bRollKeyword', e.target.value)}
                />
                <button className="btn-secondary" style={{ width: '100%', marginTop: '0.5rem', fontSize: '0.85rem' }}>
                  Regenerate B-Roll Segment
                </button>
              </div>

              <div style={{ marginTop: '2rem', padding: '1rem', background: 'var(--bg-primary)', borderRadius: '8px', border: '1px solid var(--border-color)' }}>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Block Length: {(selectedScene.durationInFrames / 30).toFixed(1)}s</p>
                <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Voice: Cartesia (Inherited)</p>
              </div>
            </div>
          ) : (
            <p className="text-muted">Select a timeline block to edit.</p>
          )}
        </div>
      </div>

      {/* Bottom: The Timeline Interface */}
      <div style={{ height: '240px', background: 'var(--bg-secondary)', borderTop: '1px solid var(--border-color)', display: 'flex', flexDirection: 'column' }}>
        
        {/* Timeline Header / Ruler */}
        <div style={{ height: '30px', background: 'var(--bg-primary)', borderBottom: '1px solid var(--border-color)', display: 'flex', position: 'relative' }}>
          {Array.from({ length: 15 }).map((_, i) => (
            <div key={i} style={{ flex: 1, borderLeft: '1px solid var(--border-color)', position: 'relative' }}>
              <span style={{ position: 'absolute', top: '4px', left: '4px', fontSize: '0.6rem', color: 'var(--text-secondary)' }}>00:{(i * 2).toString().padStart(2, '0')}</span>
            </div>
          ))}
        </div>

        {/* Tracks Area */}
        <div style={{ flex: 1, padding: '1rem', overflowX: 'auto', display: 'flex', flexDirection: 'column', gap: '0.5rem', position: 'relative' }}>
          
          {/* Playhead Mock */}
          <div style={{ position: 'absolute', top: 0, bottom: 0, left: '15%', width: '2px', background: 'red', zIndex: 10 }}></div>

          {/* Track 1: B-Roll Visuals */}
          <div style={{ display: 'flex', height: '50px', gap: '4px', width: '200%' }}>
            <div style={{ width: '80px', flexShrink: 0, color: 'var(--text-secondary)', fontSize: '0.8rem', display: 'flex', alignItems: 'center' }}>Visuals</div>
            {timeline.map((scene, i) => (
              <div 
                key={scene.id}
                onClick={() => setSelectedScene(scene)}
                style={{ 
                  flex: scene.durationInFrames, 
                  background: selectedScene?.id === scene.id ? 'var(--accent-primary)' : 'rgba(99, 102, 241, 0.4)', 
                  borderRadius: '4px', 
                  border: '1px solid var(--border-color)',
                  padding: '4px',
                  cursor: 'pointer',
                  overflow: 'hidden',
                  whiteSpace: 'nowrap',
                  textOverflow: 'ellipsis',
                  fontSize: '0.75rem'
                }}
              >
                {scene.bRollKeyword}
              </div>
            ))}
          </div>

          {/* Track 2: Audio/Voice */}
          <div style={{ display: 'flex', height: '40px', gap: '4px', width: '200%' }}>
            <div style={{ width: '80px', flexShrink: 0, color: 'var(--text-secondary)', fontSize: '0.8rem', display: 'flex', alignItems: 'center' }}>Voice</div>
            {timeline.map((scene, i) => (
              <div 
                key={`audio-${scene.id}`}
                onClick={() => setSelectedScene(scene)}
                style={{ 
                  flex: scene.durationInFrames, 
                  background: selectedScene?.id === scene.id ? '#a855f7' : 'rgba(168, 85, 247, 0.4)', 
                  borderRadius: '4px', 
                  border: '1px solid var(--border-color)',
                  padding: '4px',
                  cursor: 'pointer',
                  overflow: 'hidden',
                  whiteSpace: 'nowrap',
                  textOverflow: 'ellipsis',
                  fontSize: '0.75rem'
                }}
              >
                {scene.text}
              </div>
            ))}
          </div>

        </div>
      </div>
    </div>
  );
}
